#!/usr/bin/env bash

# VER=1.19.3
# sudo wget -c https://golang.org/dl/go$VER.linux-amd64.tar.gz
# sudo rm -rf /usr/local/go
# sudo tar -C /usr/local  -xvzf go$VER.linux-amd64.tar.gz
# sudo rm -rf go$VER.linux-amd64.tar.gz

sudo apt update
sudo apt install -y apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
apt-cache policy docker-ce
sudo apt -y install docker-ce
# sudo systemctl status docker
